export const ADD_PRODUCT_TO_SHOPPING_CART = "ADD_PRODUCT_TO_SHOPPING_CART";
export const DELETE_PRODUCT_FROM_SHOPPING_CART = "REMOVE_PRODUCT_FROM_SHOPPING_CART";
export const DELETE_PRODUCTS_WITH_STOCK_ZERO = "DELETE_PRODUCTS_WITH_STOCK_ZERO";
export const DELETE_PRODUCTS_FROM_SHOPPING_CART = "DELETE_PRODUCTS_FROM_SHOPPING_CART";

